### ISSUE TITLE
Some characters not legible

### ISSUE THREAD

**Issue by DillonRing** [mixcoac/Drakula#1]
Some letters, when displayed in Channel categories, settings categories and Hoisted roles are not legible. Examples attached below.
![not legible 4](https://user-images.githubusercontent.com/67810247/118719695-6b95a200-b7ee-11eb-8b5b-ecdf7e5602b4.png)
![not legible 3](https://user-images.githubusercontent.com/67810247/118719698-6b95a200-b7ee-11eb-845b-779548ead95f.png)
![not legible 2](https://user-images.githubusercontent.com/67810247/118719700-6b95a200-b7ee-11eb-9c3f-db903b18ca1f.png)
![not legible 1](https://user-images.githubusercontent.com/67810247/118719702-6c2e3880-b7ee-11eb-99a4-b47f1ee8e4dc.png)

**Comment by mixcoac** [comment]
Install the official Delugia Code font and check if it works, if it doesn't try and use good ol' Cascadia code

Delugia: https://github.com/adam7/delugia-code

**Comment by mixcoac** [comment]
Closing this issue as I've not gotten a response back from Dillon.
